### ISSUE TITLE
Login command should ask for the URL of the mothership being logged into

### ISSUE THREAD

**Issue by jkulton** [mothership-paas/mothership-cli#10]
- CLI should ask user the URL of the mothership they want to log into
- After logging in, the mothership URL should be saved into a mothership-cli config file and be the default HOST when issuing API commands

**Comment by bharatagarwal** [comment]
Here's the workflow I'm imagining for this:

Instead of `mothership login username password`, we make this:

```shell
$ mothership login
> What's the URL of your mothership?
....
> Username:
> Password:
```

And then show an error if there is an issue with logging in.

**Comment by jkulton** [comment]
Handled as part of #16. Thanks @bharatagarwal!
