### ISSUE TITLE
Show error message for issues with setup

### ISSUE THREAD

**Issue by bharatagarwal** [mothership-paas/mothership-cli#11]
![Screenshot 2019-12-13 at 6 00 44 PM](https://user-images.githubusercontent.com/15229351/70800608-ac57e300-1dd2-11ea-94fc-3b52e701ee65.png)

**Comment by jkulton** [comment]
I'm going to close this since we're removing the setup command, and because we've tried to handle some of the edge cases by attempting the `docker-machine create` a few times (if it fails)
